### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException: Failed to change locale for db to 'en_GB'

### ISSUE THREAD

**Issue by ravilukka** [j256/ormlite-android#108]

**Comment by j256** [comment]
No other information?  No stack trace?  Little help?

**Comment by ravilukka** [comment]
Fatal Exception: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/com.elitemobile.elitebdmpro/databases/EliteBDM.db' to 'en_GB'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:409)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:223)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:198)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:838)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:823)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:716)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:664)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
