### ISSUE TITLE
NullPointerException on queryBuilder

### ISSUE THREAD

**Issue by alexsilva** [j256/ormlite-android#14]
In Google Analytics I have the following records:
```
...
	2.	NullPointerException (@PlayList:getDatabaseAlbum:386) {Thread-108}
	3.	NullPointerException (@PlayList:getDatabaseAlbum:386) {Thread-11086}	
	4.	NullPointerException (@PlayList:getDatabaseAlbum:386) {Thread-11189}	
	5.	NullPointerException (@PlayList:getDatabaseAlbum:386) {Thread-1125}	
	6.	NullPointerException (@PlayList:getDatabaseAlbum:386) {Thread-1194}	
	7.	NullPointerException (@PlayList:getDatabaseAlbum:386) {Thread-1204}
```

On Google Play the following:

```
java.lang.NullPointerException
    at es.hol.soundmedia.PlayList.getDatabaseAlbum(PlayList.java:386)
    at es.hol.soundmedia.PlayList.access$200(PlayList.java:31)
    at es.hol.soundmedia.PlayList$3.run(PlayList.java:458)
    at java.lang.Thread.run(Thread.java:856)
```
User Reports:

Android 4.1	3	75,0%
Hoje, 00:09 (APP 4.2.7)  DROID RAZR i (smi) (PT-BR - dando erro quando escolhe musica)

Android 4.3	1	25,0%
2 de jun 11:31 (APP 4.2.4) Galaxy S3 (d2usc) Great application.

Beginning of the implementation is to get to the error:

```
    public void checkAll(final Group group, final Album album,
                         final List<Music> musics, final OnCheckListener callback){
        new Thread(new Runnable() {
            @Override
            public void run() {
                Handler handler = new Handler(Looper.getMainLooper());
                final Map<Integer,Boolean> map = new HashMap<Integer, Boolean>();
                Album _album = getDatabaseAlbum(group, album);
                if (!_album.hasValidId()) {
                    for (int index=0; index < musics.size(); index++)
                        map.put(index, false);
                    handler.post(new Runnable() {
                        @Override
                        public void run() {
                            callback.onCheckResult(map);
                        }
                    });
                    return;
                }
                for (int index=0; index < musics.size(); index++){
                    map.put(index, hasValidId(getDatabaseMusic(_album, musics.get(index))));
                }
                handler.post(new Runnable() {
                    @Override
                    public void run() {
                        callback.onCheckResult(map);
                    }
                });
            }
        }).start();
    }
```

Location of the error:

```
383    private Album getDatabaseAlbum(Group group, Album album){
384     QueryBuilder<Album, Integer> db = mAlbumDao.queryBuilder();
385     try {
386            Where<Album,Integer> where = db.where()
387                    .eq(Album.GROUP_ID_FIELD, group.getId()).and()
                    .eq(Album.ARTIST_FIELD, new SelectArg(album.getArtist())).and()
                    .eq(Album.URL_FIELD, new SelectArg(album.getUrl()));
            Album _album  = where.queryForFirst();

            if (hasValidId(_album))
                album = _album;
            else
                album.invalidateId();
        } catch (SQLException e) {
            Log.d(MainActivity.TAG, "Music", e);
            album.invalidateId();
        }
        return album;
    }
```
I see no other possibility besides 'queryBuilder'(var db) be returning null. Any idea why the error ?
```
384     QueryBuilder<Album, Integer> db = mAlbumDao.queryBuilder();
385     try {
386            Where<Album,Integer> where = db.where()
```

APP https://play.google.com/store/apps/details?id=es.hol.soundmedia

**Comment by j256** [comment]
I'm going to close this issue.  Feel free to disagree and reopen if you have some more information that this is a bug in ORMLite.  Thanks.
