### ISSUE TITLE
The application may be doing too much work on its main thread

### ISSUE THREAD

**Issue by smail2133** [j256/ormlite-android#15]
Hi Grey! I received exception when update database!!
Here is log:
{code}
00:21 I/Choreographer: Skipped 752 frames!  The application may be doing too much work on its main thread.
00:21 I/dalvikvm-heap: Grow heap (frag case) to 12.850MB for 1718978-byte allocation
00:21 I/dalvikvm-heap: Grow heap (frag case) to 16.058MB for 3409936-byte allocation
00:21 I/TableUtils: creating table 'credit_card'
00:23 I/Choreographer: Skipped 92 frames!  The application may be doing too much work on its main thread.
00:23 I/dalvikvm-heap: Grow heap (frag case) to 17.823MB for 1718976-byte allocation
00:24 I/TableUtils: executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `credit_card` (`credit_card_ccv` VARCHAR , `credit_card_address_1` VARCHAR , `credit_card_address_2` VARCHAR , `credit_card_address_city` VARCHAR , `credit_card_address_country` VARCHAR , `credit_card_address_first_name` VARCHAR , `credit_card_address_id` VARCHAR , `credit_card_address_last_name` VARCHAR , `credit_card_address_phone` VARCHAR , `credit_card_address_state` VARCHAR , `credit_card_address_zip_code` VARCHAR , `credit_card_expiration_month` VARCHAR , `credit_card_expiration_year` VARCHAR , `credit_card_full_number` VARCHAR , `credit_card_id` VARCHAR , `credit_card_last_digit` VARCHAR , `credit_card_type` VARCHAR , `credit_card_type_id` VARCHAR , `credit_card_address_uri` VARCHAR , `credit_card_name` VARCHAR , `credit_card_first_name` VARCHAR , `credit_card_user_id` VARCHAR , `credit_card_last_name` VARCHAR , `credit_card_is_saved` SMALLINT , `credit_card_is_save_required` SMALLINT , `id` INTEGER PRIMARY KEY AUTOINCREMENT ) 
00:30 I/Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
00:32 I/TableUtils: creating table 'deal'
{code}

And stack:
{code}
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
	at com.j256.ormlite.db.BaseDatabaseType.appendColumnArg(BaseDatabaseType.java:64)
	at com.j256.ormlite.table.TableUtils.addCreateTableStatements(TableUtils.java:334)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:439)
	at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:220)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:61)
	at com.ls.dailysteals.core.database.DB.onCreate(DB.java:81)
	at com.ls.dailysteals.core.database.DB.onUpgrade(DB.java:138)
	at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.onUpgrade(OrmLiteSqliteOpenHelper.java:240)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:257)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:66)
	at com.j256.ormlite.dao.BaseDaoImpl.callBatchTasks(BaseDaoImpl.java:626)
	at com.ls.***.ui.fragment.IceMonkeyFragment$3.doInBackground(IceMonkeyFragment.java:175)
	at com.ls.***.ui.fragment.IceMonkeyFragment$3.doInBackground(IceMonkeyFragment.java:170)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 3 more
{code}

{code}
@Override
	public void onUpgrade(SQLiteDatabase sqLiteDatabase, ConnectionSource connectionSource, int oldVer, int newVer) {

		// drop all tables when database version latest 4 because database structure cardinal changes.
		if (oldVer < DATABASE_VERSION) {
			List<String> tables = new ArrayList<String>();
			Cursor cursor = sqLiteDatabase.rawQuery("SELECT * FROM sqlite_master WHERE type='table';", null);
			cursor.moveToFirst();
			while (!cursor.isAfterLast()) {
				String tableName = cursor.getString(1);
				if (!tableName.equals("android_metadata") && !tableName.equals("sqlite_sequence"))
					tables.add(tableName);
				cursor.moveToNext();
			}
			cursor.close();

			for (String tableName : tables) {
				sqLiteDatabase.execSQL("DROP TABLE IF EXISTS " + tableName);
			}
		}

		onCreate(sqLiteDatabase, connectionSource);
	}
{code}

**Comment by kpgalligan** [comment]
Are you accessing the db in your main thread?

**Comment by j256** [comment]
I'm going to close this now.  It seems like you are doing db work in the main thread which is not a good idea.  Check the android docs.
