### ISSUE TITLE
Exception:queryForLong from database failed

### ISSUE THREAD

**Issue by a631855639** [j256/ormlite-android#49]
I had a BaseHelper which extends OrmLiteSqliteOpenHelper,and create the table Test.class.But,when I add the data,it throw the exception 'queryForLong from database failed: SELECT COUNT(*) FROM `tb_test111` WHERE `id` = ?'

**Comment by j256** [comment]
Please post the full exception.  Typically the cause by blocks at the bottom of the exception provide more information that should help you figure out the issue.

**Comment by 336Project** [comment]
thanks.I had solved the problem.It was caused by, don't create the table success.just upgrade version number or uninstall the application

**Comment by a631855639** [comment]
thanks.I had solved the problem.It was caused by, don't create the table success.just upgrade version number or uninstall the application

**Comment by hafsalrahman** [comment]
java.sql.SQLException: queryForLong from database failed: SELECT COUNT(*) FROM `<tablename>` WHERE `tableNameId` = ? //I'm getting this error while trying to insert data.

**Comment by j256** [comment]
Please post your own issue @hafsalrahman .

**Comment by DemuduSwamy** [comment]
android.database.sqlite.SQLiteException: no such table: activeingredient (code 1 SQLITE_ERROR)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1009)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:238)
    at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:277)
    at com.j256.ormlite.android.AndroidDatabaseResults.first(AndroidDatabaseResults.java:73)
    at com.j256.ormlite.android.AndroidDatabaseConnection.queryForOne(AndroidDatabaseConnection.java:191)
    at com.j256.ormlite.stmt.mapped.MappedQueryForId.execute(MappedQueryForId.java:38)
    at com.j256.ormlite.field.FieldType.assignField(FieldType.java:543)
    at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:71)
    at com.j256.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:270)
    at com.j256.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:161)
    at com.j256.ormlite.stmt.SelectIterator.next(SelectIterator.java:173)
    at c.a.u.a(_Collections.kt:113)
    at c.a.u.b(_Collections.kt:87)
    at au.org.nps.medicinelistplus.data.util.bdmards.k$a.a(MedicineConversionUtils.kt:1559)
    at au.org.nps.medicinelistplus.data.util.bdmards.k$a.a(MedicineConversionUtils.kt:1550)
    at au.org.nps.medicinelistplus.presentation.ui.adapter.d.e(GroupedMedicineListAdapter.kt:278)
    at au.org.nps.medicinelistplus.presentation.ui.adapter.d.a(GroupedMedicineListAdapter.kt:61)
    at au.org.nps.medicinelistplus.presentation.ui.adapter.d.a(GroupedMedicineListAdapter.kt:23)
    at androidx.recyclerview.widget.RecyclerView$a.a(RecyclerView.java:7065)
    at androidx.recyclerview.widget.RecyclerView$a.b(RecyclerView.java:7107)
    at androidx.recyclerview.widget.RecyclerView$p.a(RecyclerView.java:6012)
    at androidx.recyclerview.widget.RecyclerView$p.a(RecyclerView.java:6279)
    at androidx.recyclerview.widget.RecyclerView$p.a(RecyclerView.java:6118)
    at androidx.recyclerview.widget.RecyclerView$p.c(RecyclerView.java:6114)
    at androidx.recyclerview.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:2303)
    at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:1627)
    at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.c(LinearLayoutManager.java:665)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
    at android.view.View.measure(View.java:25988)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
    at android.view.View.measure(View.java:25988)
    at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
    at android.view.View.measure(View.java:25988)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:832)
    at android.view.View.measure(View.java:25988)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3854)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2593)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2863)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2305)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9133)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
    at android.view.Choreographer.doFrame(Choreographer.java:934)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8212)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
