### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by gao746700783** [j256/ormlite-android#70]
i have a problem which makes my app crashes
as below:
java.lang.ExceptionInInitializerError
at com.j256.ormlite.db.SqliteAndroidDatabaseType.a(SqliteAndroidDatabaseType.java:76)
at com.j256.ormlite.dao.DaoManager.a(DaoManager.java:67)
at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.getDao(OrmLiteSqliteOpenHelper.java:279)
at com.elitech.core.db.DatabaseHelper.getDao(DatabaseHelper.java:103)
at com.elitech.dicos.view.fragment.MsgTabFragment$TaskThread.run(MsgTabFragment.java:307)
Caused by: java.lang.IllegalStateException: Could not find support for DatabaseField A
at com.j256.ormlite.android.DatabaseTableConfigUtil.a(DatabaseTableConfigUtil.java:225)
at com.j256.ormlite.android.DatabaseTableConfigUtil.a(DatabaseTableConfigUtil.java:120)
at com.j256.ormlite.android.DatabaseTableConfigUtil.<clinit>(DatabaseTableConfigUtil.java:38)
... 5 more

**Comment by gao746700783** [comment]
i noticed that ,when i run released apk,it just happens,but the debug apk doesn't;
and the diff. is about the proguard options,so,this exception may happens here,i will try

**Comment by gao746700783** [comment]
proguard-rules.pro files like this:

`# OrmLite uses reflection
-keep class com.j256.**
-keepclassmembers class com.j256.** { *; }
-keep enum com.j256.**
-keepclassmembers enum com.j256.** { *; }
-keep interface com.j256.**
-keepclassmembers interface com.j256.** { *; }

-keepattributes *Annotation*

-keepclassmembers class * {
    @com.j256.ormlite.field.DatabaseField *;
}

-keepattributes Signature`

**Comment by j256** [comment]
I'm going to mark this as fixed.  Feel free to reopen.
