### ISSUE TITLE
W/SQLiteCursor: Close cursor android.database.sqlite.SQLiteCursor@xxxxx on null twice or more

### ISSUE THREAD

**Issue by michaelfomin** [j256/ormlite-android#92]
Getting a lot of warning level stack traces printed in my log.

```
W/SQLiteCursor: Close cursor android.database.sqlite.SQLiteCursor@e5e1f96 on null twice or more
                                                                              java.lang.Exception
                                                                                  at android.database.sqlite.SQLiteCursor.close(SQLiteCursor.java:250)
                                                                                  at com.j256.ormlite.android.AndroidCompiledStatement.close(AndroidCompiledStatement.java:91)
                                                                                  at com.j256.ormlite.stmt.StatementExecutor.queryForFirst(StatementExecutor.java:108)
                                                                                  at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:233)
                                                                                  at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:375)
```

Looks like this post has a fix.
https://stackoverflow.com/questions/25245249/ormlite-sqlitecursor-close-cursor-on-null-twice-or-more/26066557#26066557

Is there any plan to fix this in the official release?

**Comment by michaelfomin** [comment]
Verified this is still an issue on
ormlite-android-5.1.jar
ormlite-core-5.1.jar

**Comment by j256** [comment]
Huh.  The code has been fixed a long time ago in 2014.  See: https://github.com/j256/ormlite-android/commit/33ba0657df9c6822dbb09272d10fbe16f4260be4#diff-3e1615fd2bc46fadd68e3b8b5b465101

I'm suspicious of the line number in AndroidCompiledStatement.  You can see that the close code is on 101 now:  https://github.com/j256/ormlite-android/blob/master/src/main/java/com/j256/ormlite/android/AndroidCompiledStatement.java#L99

**Comment by michaelfomin** [comment]
Apologies, when I 'updated' to the latest 5.1, I did not do it correctly so I was still running the old 4.48 when I tried reproduced the error.
I cannot see this error on 5.1.
OK to close out.

**Comment by j256** [comment]
Phew.
